version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      cache_from:
        - frontend-nextjs:latest
    image: frontend-nextjs:latest
    container_name: frontend-nextjs
    ports:
      - "3007:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - PORT=3000
      - HOSTNAME=0.0.0.0
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
